application:
  name: currency-api
  project: currency-api
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- type: mysql
  version: "5.7"
  name: my-mysql-6132005
routers:
- name: main
  routes:
  - application_name: currency-api
    paths:
    - /*
