on: pull_request
name: on pull request merge, delete the branch
jobs:
  branchCleanup:
    name: branch cleanup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: branch cleanup
      uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
